"""modelos dominio completos

Revision ID: af25771d3f4b
Revises: 487525d6a687
Create Date: 2026-09-30 19:45:21.221601
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'af25771d3f4b'
down_revision: str | None = '487525d6a687'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Enums para tablas nuevas (se crean inline en CREATE TABLE, pero los definimos aquí para reutilizar en downgrade)
tipo_documento_enum = postgresql.ENUM('CC', 'CE', 'PASAPORTE', 'TI', 'OTRO', name='tipo_documento')
estado_reserva_enum = postgresql.ENUM('PENDIENTE', 'CONFIRMADA', 'CHECK_IN', 'CHECK_OUT', 'CANCELADA', 'NO_SHOW', name='estado_reserva')
metodo_pago_enum = postgresql.ENUM('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', 'OTRO', name='metodo_pago')
tipo_pago_enum = postgresql.ENUM('ABONO', 'PAGO_FINAL', 'REEMBOLSO', name='tipo_pago')
tipo_turno_enum = postgresql.ENUM('MANANA', 'TARDE', 'NOCHE', 'PERSONALIZADO', name='tipo_turno')

# Enum para columna agregada a tabla existente (habitaciones.limpieza)
estado_limpieza_enum = postgresql.ENUM('LIMPIA', 'SUCIA', name='estado_limpieza')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear enums explícitamente ANTES de usarlos en PostgreSQL
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        estado_limpieza_enum.create(bind, checkfirst=True)

    op.create_table(
        'refresh_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('usuario_id', sa.Integer(), nullable=False),
        sa.Column('token_hash', sa.String(length=64), nullable=False),
        sa.Column('familia_id', sa.String(length=36), nullable=False),
        sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
        sa.Column('revocado_en', sa.DateTime(timezone=True), nullable=True),
        sa.Column('user_agent', sa.String(length=512), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_refresh_tokens_usuario_id_usuarios'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
        sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash')),
    )
    op.create_table(
        'huespedes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tipo_documento', tipo_documento_enum, nullable=False),
        sa.Column('numero_documento', sa.String(length=20), nullable=False),
        sa.Column('nombres', sa.String(length=120), nullable=False),
        sa.Column('apellidos', sa.String(length=120), nullable=False),
        sa.Column('email', sa.String(length=254), nullable=True),
        sa.Column('telefono', sa.String(length=30), nullable=True),
        sa.Column('nacionalidad', sa.String(length=80), nullable=True),
        sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
        sa.Column('direccion', sa.Text(), nullable=True),
        sa.Column('observaciones', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_huespedes')),
        sa.UniqueConstraint('tipo_documento', 'numero_documento', name=op.f('uq_huespedes_tipo_numero')),
    )
    op.create_table(
        'reservas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('codigo', sa.String(length=20), nullable=False),
        sa.Column('huesped_id', sa.Integer(), nullable=False),
        sa.Column('habitacion_id', sa.Integer(), nullable=False),
        sa.Column('fecha_entrada', sa.Date(), nullable=False),
        sa.Column('fecha_salida', sa.Date(), nullable=False),
        sa.Column('numero_huespedes', sa.Integer(), nullable=False),
        sa.Column('estado', estado_reserva_enum, nullable=False),
        sa.Column('precio_noche_aplicado', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('total_estimado', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('observaciones', sa.Text(), nullable=True),
        sa.Column('motivo_cancelacion', sa.Text(), nullable=True),
        sa.Column('check_in_real', sa.DateTime(timezone=True), nullable=True),
        sa.Column('check_out_real', sa.DateTime(timezone=True), nullable=True),
        sa.Column('creada_por', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('fecha_salida > fecha_entrada', name=op.f('ck_reservas_fecha_salida_posterior')),
        sa.CheckConstraint('numero_huespedes >= 1', name=op.f('ck_reservas_huespedes_minimo')),
        sa.ForeignKeyConstraint(['habitacion_id'], ['habitaciones.id'], name=op.f('fk_reservas_habitacion_id_habitaciones'), ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['huesped_id'], ['huespedes.id'], name=op.f('fk_reservas_huesped_id_huespedes'), ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['creada_por'], ['usuarios.id'], name=op.f('fk_reservas_creada_por_usuarios'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_reservas')),
        sa.UniqueConstraint('codigo', name=op.f('uq_reservas_codigo')),
    )
    op.create_index(op.f('ix_reservas_habitacion_fechas'), 'reservas', ['habitacion_id', 'fecha_entrada', 'fecha_salida'], unique=False)
    op.create_index(op.f('ix_reservas_estado'), 'reservas', ['estado'], unique=False)
    op.create_index(op.f('ix_reservas_huesped'), 'reservas', ['huesped_id'], unique=False)
    op.create_table(
        'consumos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reserva_id', sa.Integer(), nullable=False),
        sa.Column('descripcion', sa.String(length=200), nullable=False),
        sa.Column('cantidad', sa.Integer(), nullable=False),
        sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('anulado', sa.Boolean(), nullable=False),
        sa.Column('registrado_por', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('cantidad > 0', name=op.f('ck_consumos_cantidad_positiva')),
        sa.CheckConstraint('precio_unitario >= 0', name=op.f('ck_consumos_precio_no_negativo')),
        sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], name=op.f('fk_consumos_registrado_por_usuarios'), ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], name=op.f('fk_consumos_reserva_id_reservas'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_consumos')),
    )
    op.create_table(
        'pagos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reserva_id', sa.Integer(), nullable=False),
        sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('metodo', metodo_pago_enum, nullable=False),
        sa.Column('tipo', tipo_pago_enum, nullable=False),
        sa.Column('referencia', sa.String(length=100), nullable=True),
        sa.Column('anulado', sa.Boolean(), nullable=False),
        sa.Column('motivo_anulacion', sa.Text(), nullable=True),
        sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=False),
        sa.Column('registrado_por', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('monto > 0', name=op.f('ck_pagos_monto_positivo')),
        sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], name=op.f('fk_pagos_registrado_por_usuarios'), ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], name=op.f('fk_pagos_reserva_id_reservas'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pagos')),
    )
    op.create_table(
        'horarios_empleado',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('usuario_id', sa.Integer(), nullable=False),
        sa.Column('fecha', sa.Date(), nullable=False),
        sa.Column('hora_inicio', sa.Time(), nullable=False),
        sa.Column('hora_fin', sa.Time(), nullable=False),
        sa.Column('tipo_turno', tipo_turno_enum, nullable=False),
        sa.Column('notas', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_horarios_empleado_usuario_id_usuarios'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_horarios_empleado')),
        sa.UniqueConstraint('usuario_id', 'fecha', 'hora_inicio', name=op.f('uq_horarios_usuario_fecha_inicio')),
    )
    op.create_table(
        'auditoria',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('usuario_id', sa.Integer(), nullable=True),
        sa.Column('accion', sa.String(length=100), nullable=False),
        sa.Column('entidad', sa.String(length=100), nullable=False),
        sa.Column('entidad_id', sa.Integer(), nullable=True),
        sa.Column('detalle', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('ip', sa.String(length=45), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_auditoria_usuario_id_usuarios'), ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_auditoria')),
    )
    # Agregar columna limpieza a habitaciones (enum ya creado arriba)
    op.add_column('habitaciones', sa.Column('limpieza', estado_limpieza_enum, nullable=False))
    op.alter_column('habitaciones', 'precio_por_noche',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.add_column('usuarios', sa.Column('activo', sa.Boolean(), server_default='true', nullable=False))

    # PostgreSQL-specific: ExcludeConstraint para anti-solapamiento de reservas
    if bind.dialect.name == 'postgresql':
        # Crear extensión btree_gist si no existe
        op.execute('CREATE EXTENSION IF NOT EXISTS btree_gist')
        # ExcludeConstraint sobre habitacion_id con daterange
        op.execute("""
            ALTER TABLE reservas ADD CONSTRAINT ex_reservas_solapamiento
            EXCLUDE USING gist (
                habitacion_id WITH =,
                daterange(fecha_entrada, fecha_salida, '[)') WITH &&
            ) WHERE (estado IN ('PENDIENTE', 'CONFIRMADA', 'CHECK_IN'))
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("ALTER TABLE reservas DROP CONSTRAINT IF EXISTS ex_reservas_solapamiento")

    op.drop_column('usuarios', 'activo')
    op.alter_column('habitaciones', 'precio_por_noche',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('habitaciones', 'limpieza')
    op.drop_table('auditoria')
    op.drop_table('horarios_empleado')
    op.drop_table('pagos')
    op.drop_table('consumos')
    op.drop_index(op.f('ix_reservas_huesped'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_estado'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_habitacion_fechas'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_table('huespedes')
    op.drop_table('refresh_tokens')

    # PostgreSQL: eliminar tipos ENUM creados en upgrade (orden inverso)
    if bind.dialect.name == 'postgresql':
        estado_limpieza_enum.drop(bind, checkfirst=True)
        tipo_turno_enum.drop(bind, checkfirst=True)
        tipo_pago_enum.drop(bind, checkfirst=True)
        metodo_pago_enum.drop(bind, checkfirst=True)
        estado_reserva_enum.drop(bind, checkfirst=True)
        tipo_documento_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###