"""imagenes de habitaciones

Revision ID: c8057524b437
Revises: af25771d3f4b
Create Date: 2026-10-10 10:13:26.222310
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = 'c8057524b437'
down_revision: str | None = 'af25771d3f4b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitacion_imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habitacion_id', sa.Integer(), nullable=False),
    sa.Column('ruta', sa.String(length=255), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habitacion_id'], ['habitaciones.id'], name=op.f('fk_habitacion_imagenes_habitacion_id_habitaciones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habitacion_imagenes'))
    )
    op.create_index(op.f('ix_habitacion_imagenes_habitacion_id'), 'habitacion_imagenes', ['habitacion_id'], unique=False)
    op.create_index('uq_habitacion_imagenes_principal', 'habitacion_imagenes', ['habitacion_id'], unique=True, postgresql_where=sa.text('es_principal'), sqlite_where=sa.text('es_principal'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_habitacion_imagenes_principal', table_name='habitacion_imagenes', postgresql_where=sa.text('es_principal'), sqlite_where=sa.text('es_principal'))
    op.drop_index(op.f('ix_habitacion_imagenes_habitacion_id'), table_name='habitacion_imagenes')
    op.drop_table('habitacion_imagenes')
    # ### end Alembic commands ###